// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _78sHeartbreak.Data;

#nullable disable

namespace _78sHeartbreak.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030020757_AdicionadasRespostasKanye")]
    partial class AdicionadasRespostasKanye
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("_78sHeartbreak.Models.TarotCartas", b =>
                {
                    b.Property<int>("CartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartaId"));

                    b.Property<string>("Arcano")
                        .HasColumnType("longtext");

                    b.Property<string>("Confirmacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Elemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Significado")
                        .HasColumnType("longtext");

                    b.Property<string>("Vicios")
                        .HasColumnType("longtext");

                    b.Property<string>("Virtudes")
                        .HasColumnType("longtext");

                    b.HasKey("CartaId");

                    b.ToTable("TarotCartas");
                });
#pragma warning restore 612, 618
        }
    }
}
